### ISSUE TITLE
How to support polling multiple UCS Domains

### ISSUE THREAD

**Issue by dwebr** [MarshallWace/prometheus-ucs-exporter#2]
Is it possible to support polling of multiple UCS domains using a single prometheus instance or is it better to dedicate a prmetheus container to each UCS domain?

**Comment by uberspot** [comment]
We actually run separate exporters per domain. This also has the benefit of breaking monitoring into separate failure domains. 
Would that work in your use case?

**Comment by bilbof** [comment]
This is currently supported - you don't need to run multiple containers.

For multiple domains run a single container and use the `host` query param, e.g. `/metrics?host=domain.example.org` (note you will need to omit the host environment variable).
